---
title: "HW5"
output: html_document
author: "Gianna Zinnen"
date: "12-01-2025"
---

Recreate the graph shown below. It shows monthly homicides in Baltimore, with a reference added for the date of the arrest of Freddie Gray and color used to show colder months (November through April) versus warmer months (May through October). There is a smooth line added to help show seasonal and long-term trends in this data.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading all libraries needed:
library(dplyr)
library(readr)
library(lubridate)
library(stringr)
library(tidyr)
library(tidyverse)
library(broom)
library(ggplot2)
library(ggthemes)
library(scales)
library(purrr)


```



```{r data set up, warning = FALSE}

homicides <- read_csv("data/homicide-data.csv")

homicides <- homicides %>%
  mutate(city_name = paste(city, state, sep = ", "))

head(homicides)

Baltimore <- homicides %>% 
  filter(city_name == "Baltimore, MD") %>%
  mutate(Date = ymd(reported_date)) %>%  
  mutate(Year = year(Date)) %>%
  mutate(Month = month(Date)) %>%
  group_by(Year, Month) %>%
  summarize(Monthly_homicides = n(), .groups = 'drop') %>%
  ungroup() %>%
  mutate(Winter = Month %in% c(11, 12, 1, 2, 3, 4)) %>%
  mutate(Summer = Month %in% c(5, 6, 7, 8, 9, 10)) %>%
  mutate(Season = ifelse(Winter, "Winter", "Summer")) %>%
  mutate(Date = ym(paste(Year, Month)))

```


making the graph

```{r graph fig.width = 4.5, fig.height = 8, warning=FALSE}

Baltimore %>%
  ggplot(aes(x = Date, y = Monthly_homicides)) + 
  geom_col(aes(fill = Season)) +
  scale_fill_manual(values = c("Summer" = "lightgray", "Winter" = "lightblue")) +
  labs(x = "Date", y = "Monthly Homicides", title = "Homicides in Baltimore, MD") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_dark() +
  geom_vline(xintercept = as.Date("2015-04-12"), linetype = "dashed", color = "red") + 
  geom_text(aes(x = as.Date("2015-04-12"), y = 43, label = "Arrest of\nFreddie Gray"), hjust = -0.01, color = "white") +
  theme(legend.position = "bottom", legend.justification = "center", legend.title = NULL) +
  #geom_line(color = "blue", size = 1) 
  geom_smooth(method = "loess", color = "dodgerblue", se = FALSE, size = 1, span = 0.1) 



#need to fix trendline and add correct size


```
